defaults:
  - model: deepspeech2
  - metrics: inference
  - datasets: libri_test_clean
  - dataloader: example
  - transforms: example_only_instance
  - _self_

text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  decoder_type: argmax

inferencer:
  device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  from_pretrained: "best_model/model_best.pth"
  save_path: "logs/predictions"
  seed: 42
