defaults:
  - model: deepspeech2
  - writer: wandb
  - metrics: example
  - datasets: libri_clean_460
  - dataloader: train
  - transforms: soft_spec_augs_only_instance
  - _self_

writer:
  run_name: "train_460h_amp"

optimizer:
  _target_: torch.optim.AdamW
  lr: ${lr_scheduler.max_lr}
  weight_decay: 1e-6

lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 3e-4
  pct_start: 0.1
  epochs: ${trainer.n_epochs}
  anneal_strategy: cos

loss_function:
  _target_: src.loss.CTCLossWrapper
  zero_infinity: True

text_encoder:
  _target_: src.text_encoder.CTCTextEncoder

trainer:
  log_step: 100
  n_epochs: 60
  max_grad_norm: 10
  device_tensors: ["spectrogram", "text_encoded"]
  resume_from: null
  device: auto
  override: True
  monitor: "min val_WER_(Argmax)"
  save_period: 2
  early_stop: 20
  save_dir: "training/${writer.run_name}"
  seed: 42
  use_amp: True
  gradient_accumulation_steps: 2
