defaults:
  - model: deepspeech2_large
  - writer: wandb
  - metrics: example
  - datasets: libri_full
  - dataloader: train_full
  - transforms: moderate_spec_augs_only_instance
  - _self_

writer:
  run_name: "train_full"

optimizer:
  _target_: torch.optim.AdamW
  lr: ${lr_scheduler.max_lr}
  weight_decay: 5e-5

lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 3e-4
  pct_start: 0.15
  epochs: ${trainer.n_epochs}
  anneal_strategy: cos

loss_function:
  _target_: src.loss.CTCLossWrapper
  zero_infinity: True

text_encoder:
  _target_: src.text_encoder.CTCTextEncoder

trainer:
  use_amp: True
  gradient_accumulation_steps: 2
  log_step: 100
  n_epochs: 60
  max_grad_norm: 10
  device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)
  resume_from: null
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "min val_WER_(Argmax)" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 1 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: 15 # ${trainer.n_epochs} # epochs for early stopping
  save_dir: "training/${writer.run_name}"
  seed: 42
